<?php
/**
 * Custom posts for use with this theme
 */

add_action( 'init', 'custom_post_type', 0 );
/**
 * Register Custom Post Type
 */
function custom_post_type() {
	// Register Practice Area Custom Post Type
	$labels_practice = array(
		'name'                  => _x( 'Practice Areas', 'practice areas', 'text_domain' ),
		'singular_name'         => _x( 'Practice Area', 'practice', 'text_domain' ),
		'menu_name'             => __( 'Practice Areas', 'text_domain' ),
		'name_admin_bar'        => __( 'Practice Areas', 'text_domain' ),
		'archives'              => __( 'Practice Areas Archives', 'text_domain' ),
		'attributes'            => __( 'Practice Areas Attributes', 'text_domain' ),
		'parent_item_colon'     => __( 'Parent Practice Areas:', 'text_domain' ),
		'all_items'             => __( 'All Practice Areas', 'text_domain' ),
		'add_new_item'          => __( 'Add Practice Area', 'text_domain' ),
		'add_new'               => __( 'Add Practice Area', 'text_domain' ),
		'new_item'              => __( 'New Practice Area', 'text_domain' ),
		'edit_item'             => __( 'Edit Practice Area', 'text_domain' ),
		'update_item'           => __( 'Update Practice Area', 'text_domain' ),
		'view_item'             => __( 'View Practice Area', 'text_domain' ),
		'view_items'            => __( 'View Practice Areas', 'text_domain' ),
		'search_items'          => __( 'Search Practice Areas', 'text_domain' ),
		'not_found'             => __( 'Not found', 'text_domain' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'text_domain' ),
		'featured_image'        => __( 'Featured Image', 'text_domain' ),
		'set_featured_image'    => __( 'Set featured image', 'text_domain' ),
		'remove_featured_image' => __( 'Remove featured image', 'text_domain' ),
		'use_featured_image'    => __( 'Use as featured image', 'text_domain' ),
		'insert_into_item'      => __( 'Insert into Practice', 'text_domain' ),
		'uploaded_to_this_item' => __( 'Uploaded to this Practice', 'text_domain' ),
		'items_list'            => __( 'Practice Areas list', 'text_domain' ),
		'items_list_navigation' => __( 'Practice Areas list navigation', 'text_domain' ),
		'filter_items_list'     => __( 'Filter Practice Areas list', 'text_domain' ),
	);
	$args_practice   = array(
		'label'               => __( 'Practice Areas', 'text_domain' ),
		'description'         => __( 'Practice Areas post type', 'text_domain' ),
		'labels'              => $labels_practice,
		'supports'            => array( 'title', 'custom-fields', 'page-attributes', 'thumbnail', 'excerpt', 'editor' ),
		'hierarchical'        => true,
		'public'              => true,
		'show_ui'             => true,
		'show_in_menu'        => true,
		'show_in_rest'        => true,
		'menu_position'       => 5,
		'show_in_admin_bar'   => true,
		'show_in_nav_menus'   => true,
		'can_export'          => true,
		'has_archive'         => false,
		'exclude_from_search' => false,
		'publicly_queryable'  => true,
		'capability_type'     => 'post',
		'rewrite'             => array(
			'slug'       => 'practice',
			'with_front' => false,
		),
	);
	register_post_type( 'practice', $args_practice );

	// Register City Custom Post Type
	$labels_city = array(
		'name'                  => _x( 'Cities', 'cities', 'text_domain' ),
		'singular_name'         => _x( 'City', 'practice', 'text_domain' ),
		'menu_name'             => __( 'Cities', 'text_domain' ),
		'name_admin_bar'        => __( 'Cities', 'text_domain' ),
		'archives'              => __( 'Cities Archives', 'text_domain' ),
		'attributes'            => __( 'Cities Attributes', 'text_domain' ),
		'parent_item_colon'     => __( 'Parent Cities:', 'text_domain' ),
		'all_items'             => __( 'All Cities', 'text_domain' ),
		'add_new_item'          => __( 'Add City', 'text_domain' ),
		'add_new'               => __( 'Add City', 'text_domain' ),
		'new_item'              => __( 'New City', 'text_domain' ),
		'edit_item'             => __( 'Edit City', 'text_domain' ),
		'update_item'           => __( 'Update City', 'text_domain' ),
		'view_item'             => __( 'View City', 'text_domain' ),
		'view_items'            => __( 'View Cities', 'text_domain' ),
		'search_items'          => __( 'Search Cities', 'text_domain' ),
		'not_found'             => __( 'Not found', 'text_domain' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'text_domain' ),
		'featured_image'        => __( 'Featured Image', 'text_domain' ),
		'set_featured_image'    => __( 'Set featured image', 'text_domain' ),
		'remove_featured_image' => __( 'Remove featured image', 'text_domain' ),
		'use_featured_image'    => __( 'Use as featured image', 'text_domain' ),
		'insert_into_item'      => __( 'Insert into Practice', 'text_domain' ),
		'uploaded_to_this_item' => __( 'Uploaded to this Practice', 'text_domain' ),
		'items_list'            => __( 'Cities list', 'text_domain' ),
		'items_list_navigation' => __( 'Cities list navigation', 'text_domain' ),
		'filter_items_list'     => __( 'Filter Cities list', 'text_domain' ),
	);
	$args_city   = array(
		'label'               => __( 'Cities', 'text_domain' ),
		'description'         => __( 'Cities post type', 'text_domain' ),
		'labels'              => $labels_city,
		'supports'            => array( 'title', 'custom-fields', 'page-attributes', 'thumbnail', 'excerpt', 'editor' ),
		'hierarchical'        => true,
		'public'              => true,
		'show_ui'             => true,
		'show_in_menu'        => true,
		'show_in_rest'        => true,
		'menu_position'       => 5,
		'show_in_admin_bar'   => true,
		'show_in_nav_menus'   => true,
		'can_export'          => true,
		'has_archive'         => false,
		'exclude_from_search' => false,
		'publicly_queryable'  => true,
		'capability_type'     => 'post',
		'rewrite'             => array(
			'slug'       => 'areas-we-serve',
			'with_front' => false,
		),
	);
	register_post_type( 'city', $args_city );

	// Register FAQs Custom Post Type
	$labels_faq = array(
		'name'                  => _x( 'FAQs', 'faqs', 'text_domain' ),
		'singular_name'         => _x( 'FAQ', 'faq', 'text_domain' ),
		'menu_name'             => __( 'FAQs', 'text_domain' ),
		'name_admin_bar'        => __( 'FAQs', 'text_domain' ),
		'archives'              => __( 'FAQs Archives', 'text_domain' ),
		'attributes'            => __( 'FAQs Attributes', 'text_domain' ),
		'parent_item_colon'     => __( 'Parent FAQs:', 'text_domain' ),
		'all_items'             => __( 'All FAQs', 'text_domain' ),
		'add_new_item'          => __( 'Add FAQ', 'text_domain' ),
		'add_new'               => __( 'Add FAQ', 'text_domain' ),
		'new_item'              => __( 'New FAQ', 'text_domain' ),
		'edit_item'             => __( 'Edit FAQ', 'text_domain' ),
		'update_item'           => __( 'Update FAQ', 'text_domain' ),
		'view_item'             => __( 'View FAQ', 'text_domain' ),
		'view_items'            => __( 'View FAQs', 'text_domain' ),
		'search_items'          => __( 'Search FAQs', 'text_domain' ),
		'not_found'             => __( 'Not found', 'text_domain' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'text_domain' ),
		'featured_image'        => __( 'Featured Image', 'text_domain' ),
		'set_featured_image'    => __( 'Set featured image', 'text_domain' ),
		'remove_featured_image' => __( 'Remove featured image', 'text_domain' ),
		'use_featured_image'    => __( 'Use as featured image', 'text_domain' ),
		'insert_into_item'      => __( 'Insert into Practice', 'text_domain' ),
		'uploaded_to_this_item' => __( 'Uploaded to this Practice', 'text_domain' ),
		'items_list'            => __( 'FAQs list', 'text_domain' ),
		'items_list_navigation' => __( 'FAQs list navigation', 'text_domain' ),
		'filter_items_list'     => __( 'Filter FAQs list', 'text_domain' ),
	);
	$args_faq   = array(
		'label'               => __( 'FAQs', 'text_domain' ),
		'description'         => __( 'FAQs post type', 'text_domain' ),
		'labels'              => $labels_faq,
		'supports'            => array( 'title', 'custom-fields', 'page-attributes', 'thumbnail', 'excerpt', 'editor' ),
		'hierarchical'        => true,
		'public'              => true,
		'show_ui'             => true,
		'show_in_menu'        => true,
		'show_in_rest'        => true,
		'menu_position'       => 5,
		'show_in_admin_bar'   => true,
		'show_in_nav_menus'   => true,
		'can_export'          => true,
		'has_archive'         => false,
		'exclude_from_search' => false,
		'publicly_queryable'  => true,
		'capability_type'     => 'post',
		'rewrite'             => array(
			'slug'       => 'faqs',
			'with_front' => false,
		),
	);
	register_post_type( 'faq', $args_faq );

	// Register Case Result Custom Post Type
	$labels_case = array(
		'name'                  => _x( 'Case Results', 'case results', 'text_domain' ),
		'singular_name'         => _x( 'Case Result', 'case_result', 'text_domain' ),
		'menu_name'             => __( 'Case Results', 'text_domain' ),
		'name_admin_bar'        => __( 'Case Results', 'text_domain' ),
		'archives'              => __( 'Case Results Archives', 'text_domain' ),
		'attributes'            => __( 'Case Results Attributes', 'text_domain' ),
		'parent_item_colon'     => __( 'Parent Case Results:', 'text_domain' ),
		'all_items'             => __( 'All Case Results', 'text_domain' ),
		'add_new_item'          => __( 'Add Case Result', 'text_domain' ),
		'add_new'               => __( 'Add Case Result', 'text_domain' ),
		'new_item'              => __( 'New Case Result', 'text_domain' ),
		'edit_item'             => __( 'Edit Case Result', 'text_domain' ),
		'update_item'           => __( 'Update Case Result', 'text_domain' ),
		'view_item'             => __( 'View Case Result', 'text_domain' ),
		'view_items'            => __( 'View Case Results', 'text_domain' ),
		'search_items'          => __( 'Search Case Results', 'text_domain' ),
		'not_found'             => __( 'Not found', 'text_domain' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'text_domain' ),
		'featured_image'        => __( 'Featured Image', 'text_domain' ),
		'set_featured_image'    => __( 'Set featured image', 'text_domain' ),
		'remove_featured_image' => __( 'Remove featured image', 'text_domain' ),
		'use_featured_image'    => __( 'Use as featured image', 'text_domain' ),
		'insert_into_item'      => __( 'Insert into Practice', 'text_domain' ),
		'uploaded_to_this_item' => __( 'Uploaded to this Practice', 'text_domain' ),
		'items_list'            => __( 'Case Results list', 'text_domain' ),
		'items_list_navigation' => __( 'Case Results list navigation', 'text_domain' ),
		'filter_items_list'     => __( 'Filter Case Results list', 'text_domain' ),
	);
	$args_case   = array(
		'label'               => __( 'Case Results', 'text_domain' ),
		'description'         => __( 'Case Results post type', 'text_domain' ),
		'labels'              => $labels_case,
		'supports'            => array( 'title' ),
		'hierarchical'        => true,
		'public'              => false,
		'show_ui'             => true,
		'show_in_menu'        => true,
		'show_in_rest'        => true,
		'menu_position'       => 5,
		'show_in_admin_bar'   => true,
		'show_in_nav_menus'   => true,
		'can_export'          => true,
		'has_archive'         => false,
		'exclude_from_search' => false,
		'publicly_queryable'  => true,
		'capability_type'     => 'post',
	);
	register_post_type( 'case_result', $args_case );
}
