on:
  push:
    branches:
      - main
name: 🚀 Deploy Live on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.LIVE_PORT }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          # git update to latest codebase on main branch
          cd /www/montlickwp_290/public/wp-content/themes/montlick && git pull origin main